# Generated by Django 3.2.4 on 2021-06-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210609_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='seller.seller'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='seller.seller'),
        ),
    ]
